language: node_js
sudo: false
node_js:
  - '0.10'
before_install:
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xjf phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - sudo rm -rf /usr/local/phantomjs/bin/phantomjs
  - sudo mv phantomjs /usr/local/phantomjs/bin/phantomjs
install:
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
before_script:
  - npm install
script: npm run travis
